site_name: ostis-ps-lib
dev_addr: 127.0.0.1:8021
repo_url: https://github.com/ostis-ai/ostis-ps-lib
edit_uri: edit/main/docs/

site_dir: ../../site
docs_dir: ..

exclude_docs: |
  /README.md
  build
  cmake
  common/common
  non-atomic-action-interpreter-module/non-atomic-action-interpreter-module
  scripts

extra_css:
  - _docs/_assets/main.css
extra_javascript:
  - _docs/_assets/main.js

nav:
  - Home: index.md
  - Components:
      - Library of Common Utilities: common/README.md
      - Non-Atomic Action Interpreter Module: non-atomic-action-interpreter-module/README.md
  - Development:
      - Contributing Guide: _docs/CONTRIBUTING.md
      - Codestyle Guide: https://ostis-ai.github.io/ostis-ps-lib/dev/codestyle/
  - License: https://github.com/ostis-ai/ostis-ps-lib/blob/main/LICENSE
  - Changelog: _docs/changelog.md

plugins:
   - search:
      lang: en
      separator: '[\s\-\.]+'

theme: 
  name: material
  favicon: _docs/ostis-logo.png
  logo: _docs/ostis-logo.png
  palette:  # Defines color schemes for light and dark modes
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant       # Enables instant loading of pages
    - navigation.tracking      # Automatically focuses active section in sidebar
    - navigation.tabs          # Adds top-level sections as tabs
    - navigation.sections      # Renders top-level sections as groups in sidebar
    - navigation.expand        # Expands all collapsible sections by default
    - navigation.top           # Adds a "back to top" button
    - search.suggest           # Displays search suggestions 
    - search.highlight         # Highlights search terms on result page
    - content.action.edit      # Adds links to edit doc files
    - content.tabs.link        # Shares link when clicking on a tab
    - content.code.copy        # Adds a copy button to code blocks

markdown_extensions:
  - admonition                 # Allows creation of call-out boxes (e.g., notes, warnings)
  - codehilite
  - md_in_html                 # Allows Markdown syntax inside HTML blocks
  - pymdownx.highlight:        # Enhances code block highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite      # Enables inline code highlighting
  - pymdownx.details           # Allows creating collapsible elements
  - pymdownx.superfences       # Enables advanced fenced code blocks
