name: Test ps-common-lib

on:
  pull_request:
    branches: [main]
    paths:
      - 'ps-common-lib/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-ps-common-lib:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run common checks for ps-common-lib component
        uses: ostis-ai/test-conan@0.1.0
        with:
          directory: 'ps-common-lib'
          configure-preset: release-with-tests-conan
          build-preset: release
