name: Test non-atomic-action-interpreter-module

on:
  pull_request:
    branches: [main]
    paths:
      - 'non-atomic-action-interpreter-module/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-non-atomic-action-interpreter-module:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run common checks for non-atomic-action-interpreter-module component
        uses: ostis-ai/test-conan@0.1.0
        with:
          directory: 'non-atomic-action-interpreter-module'
          configure-preset: release-with-tests-conan
          build-preset: release
